server:
  port: 8080
encoder:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  iteration: 20
  keylength: 256
jjwt:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  expirationTime: 864000
spring:
  data:
    mongodb:
      database: 123
      uri: mongodb://worker01:27017/otakuy-music-wiki
  mail:
    host: smtp.qq.com
    username: 403827354@qq.com
    password: mgysdtrrgxzsbhie
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
douban:
  authorization: Bearer 04d942e39740bf650e8bc8aac5c23e2f
mail:
  content:
sina:
  username:
  password:
