server:
  port: 80
encoder:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  iteration: 20
  keylength: 256
jjwt:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  expirationTime: 28800
spring:
  data:
    mongodb:
      database: 123
      uri: mongodb://192.168.123.150:27017/123
  mail:
    host: smtp.qq.com
    username: 403827354@qq.com
    password: mgysdtrrgxzsbhie
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
douban:
  authorization: Bearer 3b436c09829cb2e6b1ca441c87d618b2
mail:
  content:


